[build]
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.yourdomain.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  EXPO_PUBLIC_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  EXPO_PUBLIC_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  EXPO_PUBLIC_ENVIRONMENT = "development"